### ISSUE TITLE
format colapsed for sqldeveloper 21.4.0.346

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-and-sql-coding-guidelines#121]
Format colapsed in sqldevloper 21.4.0.346 and plsql-formatter-setting-main.zip file from 15.12.2021

Error in console:
Symbol 'xmlelement[41,54)' not found
Symbol 'xmlelement[58,78)' not found
Symbol 'JSON_OBJECT' not found
incrementalAlignments callback: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
.........

**Comment by PhilippSalvisberg** [comment]
You are using the provided (default) Arbori program which is part of SQLDev 21.2.1 (or something similar). After upgrading to  SQLDev 21.4.0 you need either to reset the Arbori program or import the settings provided in this repo. Then you should not see these error messages anymore.

**Comment by RichardSoule** [comment]
With SQL Developer 21.4 and a fresh download and import of the SQL Developer trivadis_advanced_format.xml and trivadis_advanced_format.abori files following the directions in the repo, a CTRL-F7 on the following statement gives me this output...
`with target_list as ( select unique target_name , metric_column , target_guid , metric_guid from mgmt$target_type where target_type
 in ( 'oracle_pdb' , 'oracle_database' ) and metric_name = 'tbspAllocation' and metric_column in ( 'spaceUsed' , 'spaceAllocated' ) ) ,
 space_used_list as ( select * from target_list where metric_column = 'spaceUsed' ) , space_allocated_list as ( select * from
 target_list where metric_column = 'spaceAllocated' ) , last_night_space_used as ( select mgmt$metric_daily . target_name , target_guid ,
 round ( sum ( average / 1024 ) ) as total_current_used_gb from mgmt$metric_daily join space_used_list using ( target_guid , metric_guid )
 where rollup_timestamp = trunc ( systimestamp - interval '1' day ) group by mgmt$metric_daily . target_name , target_guid ) ,
 last_night_space_allocated as ( select mgmt$metric_daily . target_name , target_guid , round ( sum ( average / 1024 ) ) as total_current_allocated_gb
 from mgmt$metric_daily join space_allocated_list using ( target_guid , metric_guid ) where rollup_timestamp = trunc ( systimestamp -
 interval '1' day ) group by mgmt$metric_daily . target_name , target_guid ) , last_month_space_used as ( select mgmt$metric_daily .
 target_name , target_guid , round ( sum ( average / 1024 ) ) as total_last_month_used_gb from mgmt$metric_daily join space_used_list
 using ( target_guid , metric_guid ) where rollup_timestamp = trunc ( add_months ( systimestamp , - 1 ) ) group by mgmt$metric_daily .
 target_name , target_guid ) , six_month_ago_space_used as ( select mgmt$metric_daily . target_name , target_guid , round ( sum (
 average / 1024 ) ) as total_six_month_ago_used_gb from mgmt$metric_daily join space_used_list using ( target_guid , metric_guid )
 where rollup_timestamp = trunc ( add_months ( systimestamp , - 6 ) ) group by mgmt$metric_daily . target_name , target_guid ) ,
 results as ( select last_night_space_allocated . target_name , total_current_allocated_gb as current_allocated_gb , total_current_allocated_gb -
 total_current_used_gb as current_free_gb , total_current_used_gb as current_used_gb , total_last_month_used_gb as last_month_used_gb ,
 total_six_month_ago_used_gb as six_month_ago_gb , total_current_used_gb - total_last_month_used_gb as last_month_growth_gb ,
 total_current_used_gb - total_six_month_ago_used_gb as six_month_growth_gb , round ( ( total_current_used_gb - total_six_month_ago_used_gb ) /
 6 ) as average_six_month_growth from last_night_space_allocated join last_night_space_used using ( target_guid ) join last_month_space_used
 using ( target_guid ) join six_month_ago_space_used using ( target_guid ) ) select * from results order by last_month_growth_gb
 desc ;`

**Comment by RichardSoule** [comment]
I think this is what Richard Wiener meant by 'format colapsed'.
